version: '3.1'
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - sample
networks:
  sample: