# Generated by Django 4.1.7 on 2023-03-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='updated',
            field=models.DateTimeField(default=None),
        ),
    ]
