# Generated by Django 4.1.7 on 2023-03-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_alter_schema_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
