# Generated by Django 4.1.7 on 2023-03-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_alter_schema_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='updated',
            field=models.DateField(default=None, null=True),
        ),
    ]
