# Generated by Django 4.1.7 on 2023-03-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_alter_schema_created_alter_schema_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schema',
            name='updated',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
