# Generated by Django 4.1.7 on 2023-03-24 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_alter_schema_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='schema',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
